### ISSUE TITLE
Compressed files in Melnikov dataset

### ISSUE THREAD

**Issue by afrubin** [rraadd88/ms_datasets#2]
The files downloaded by `get_seq_data.py` for Melnikov_et_al_2014 are compressed as `.fastq.bz2`, but `dms2dfe` expects these files to be `.fastq`. Decompressing the files in `'ms_datasets/analysis/Melnikov_et_al_2014/data_input'` allows the program to run.

**Comment by rraadd88** [comment]
Thanks for pointing out. Actually, command for decompressing `.bz2` existed in the `get_seq_data.py` but had a problem. A `-d` argument in `bzip2 -d` was missing.
Now it's fixed.
